/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 */
#ifndef _CLOCK_GROUP_QCOM_H_
#define _CLOCK_GROUP_QCOM_H_

#define TURING_QDSP6SS_DBG_CFG			0x300018
#define TURING_QDSP6SS_RET_CFG			0x30001c
#define TURING_QDSP6SS_CORE_CBCR		0x300020
#define TURING_QDSP6SS_XO_CBCR			0x300038
#define TURING_QDSP6SS_SLEEP_CBCR		0x30003c
#define TURING_QDSP6SS_CORE_CMD_RCGR		0x300028
#define TURING_QDSP6SS_CORE_CFG_RCGR		0x30002c
#define TURING_QDSP6SS_BOOT_CORE_START		0x300400
#define TURING_QDSP6SS_BOOT_CMD			0x300404
#define TURING_QDSP6SS_BOOT_STATUS		0x300408

#define RET_CFG_RET_ARES_ENA_BIT		BIT(0)
#define CORE_CBCR_CLKEN_BIT			BIT(0)
#define XO_CBCR_CLKEN_BIT			BIT(0)
#define SLEEP_CBCR_CLKEN_BIT			BIT(0)
#define CORE_CMD_RCGR_UPDATE_BIT		BIT(0)
#define BOOT_CORE_START_START_BIT		BIT(0)
#define BOOT_STATUS_STATUS_BIT			BIT(0)

#define TURING_Q6RCG_CFG_VAL			0x100101

#define TURING_AON_CMD_RCGR			0x5000
#define TURING_AON_CFG_RCGR			0x5004
#define TURING_TURING_WRAPPER_AON_CBCR		0x5098

#define AON_CMD_RCGR_UPDATE_BIT			BIT(0)
#define AON_CFG_RCGR_SRC_SEL_MASK		0x700
#define AON_CFG_RCGR_SRC_SEL_SHIFT		8
#define WRAPPER_AON_CBCR_CLK_ENABLE_BIT		BIT(0)
#define WRAPPER_AON_CBCR_CLK_OFF_BIT		BIT(31)

#define TURING_Q6SS_AHBM_AON_CBCR		0x9000
#define TURING_Q6SS_AHBS_AON_CBCR		0x10000

#define Q6SS_AHB_CBCR_CLK_ENABLE_BIT		BIT(0)
#define Q6SS_AHB_CBCR_CLK_OFF_BIT		BIT(31)

/* Spark PLL sub-offsets (SPARK_PLL_*) are declared in clock-qcom.c. */
#define TURING_QDSP6SS_PLL_BASE_OFFSET		0x300200

#define GCC_TURING_CFG_AHB_CBCR			0xab01c
#define GCC_COMPUTESS_RESTART			0xc3000

#define TURING_CFG_AHB_CBCR_CLK_ENABLE_BIT	BIT(0)
#define TURING_CFG_AHB_CBCR_CLK_OFF_BIT		BIT(31)

#define GCC_MCU_PROC_H_CBCR			0xaa034
#define GCC_MCU_DBG_CBCR			0xaa02c
#define GCC_MCU_AXI_M_CBCR			0xaa05c
#define GCC_MCU_AHB_CBCR			0xaa010
#define GCC_SYS_NOC_MCU_AHB_CBCR		0x10dc4
#define GCC_MCU_F_CBCR				0xaa030
#define GCC_MCU_SS_H_CBCR			0xaa03c
#define GCC_MCU_SS_H_UNCOL_CBCR			0xaa040
#define GCC_MCU_TMR_CBCR			0xaa04c
#define GCC_MCU_SLEEP_CBCR			0xaa058
#define GCC_MCU_F_CFG_RCGR			0xaa018
#define GCC_MCU_F_CMD_RCGR			0xaa014
#define GCC_MCU_AHB_CFG_RCGR			0xaa074
#define GCC_MCU_RESTART				0xb3000

#define MCU_PROC_H_CBCR_CLK_ARES_BIT		BIT(2)
#define MCU_PROC_H_CBCR_CLK_ENABLE_BIT		BIT(0)
#define MCU_PROC_H_CBCR_CLK_OFF_BIT		BIT(31)
#define MCU_DBG_CBCR_CLK_ENABLE_BIT		BIT(0)
#define MCU_AXI_M_CBCR_CLK_ENABLE_BIT		BIT(0)
#define MCU_AHB_CBCR_CLK_ENABLE_BIT		BIT(0)
#define SYS_NOC_MCU_AHB_CBCR_CLK_ENABLE_BIT	BIT(0)
#define MCU_F_CBCR_CLK_ENABLE_BIT		BIT(0)
#define MCU_SS_H_CBCR_CLK_ENABLE_BIT		BIT(0)
#define MCU_SS_H_UNCOL_CBCR_CLK_ENABLE_BIT	BIT(0)
#define MCU_TMR_CBCR_CLK_ENABLE_BIT		BIT(0)
#define MCU_SLEEP_CBCR_CLK_ENABLE_BIT		BIT(0)
#define MCU_F_CFG_RCGR_SRC_SEL_MASK		0x700
#define MCU_F_CFG_RCGR_SRC_SEL_SHIFT		8
#define MCU_F_CFG_RCGR_SRC_DIV_MASK		0x1f
#define MCU_F_CFG_RCGR_SRC_DIV_SHIFT		0
#define MCU_F_CMD_RCGR_UPDATE_BIT		BIT(0)
#define MCU_AHB_CFG_RCGR_SRC_SEL_MASK		0x700
#define MCU_AHB_CFG_RCGR_SRC_SEL_SHIFT		8
#define MCU_AHB_CFG_RCGR_SRC_DIV_MASK		0x1f
#define MCU_AHB_CFG_RCGR_SRC_DIV_SHIFT		0
#define MCU_RESTART_SS_RESTART_BIT		BIT(0)

#define TCSR_TURING_HALTREQ			0x74000
#define TCSR_TURING_HALTACK			0x74004
#define TCSR_TURING_MASTER_IDLE			0x74008
#define TCSR_TURING_PWR_ON			0x7400c

#define TCSR_TURING_HALTREQ_BIT			BIT(0)
#define TCSR_TURING_HALTACK_BIT			BIT(0)
#define TCSR_TURING_MASTER_IDLE_BIT		BIT(0)
#define TCSR_TURING_PWR_ON_BIT			BIT(0)

#define MCU_RVCP_TILE0_BOOT_SUPPRESS		0x8c100

#endif /* _CLOCK_GROUP_QCOM_H_ */
