/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef QTI_ICBID_H
#define QTI_ICBID_H

enum icbid_master {
	ICBID_MASTER_APPSS_PROC = 0,
	ICBID_MASTER_MNOC_HF_MEM_NOC,
	ICBID_MASTER_MDP0,
	ICBID_MASTER_CRYPTO_CORE0,
	ICBID_MASTER_CRYPTO_CORE1,
	ICBID_MASTER_QUP_2,
	ICBID_MASTER_QUP_1,
	ICBID_MASTER_PCIE_0,
	ICBID_MASTER_PCIE_1,
	ICBID_MASTER_EMAC,
	ICBID_MASTER_SNOC_SF_MEM_NOC,
	ICBID_MASTER_A1NOC_SNOC,
	ICBID_MASTER_A2NOC_SNOC,
	ICBID_MASTER_ANOC_PCIE_GEM_NOC,
	ICBID_MASTER_CDSP_PROC,
	ICBID_MASTER_LLCC,
	ICBID_MASTER_IPA_CORE,
	ICBID_MASTER_QUP_0,
	ICBID_MASTER_COMPUTE_NOC,
	ICBID_MASTER_QUP_CORE_1,
	ICBID_MASTER_QUP_CORE_2,
	ICBID_MASTER_QUP_CORE_0,
	ICBID_MASTER_GEM_NOC_CNOC,
	ICBID_MASTER_PKA_CORE,
	ICBID_MASTER_HWKM_CORE,
	ICBID_MASTER_EMAC_1,
	ICBID_MASTER_CDSP_PROC_B,
	ICBID_MASTER_COMPUTE_NOC_1,
	ICBID_MASTER_QUP_3,
	ICBID_MASTER_DSP0,
	ICBID_MASTER_DSP1,
	ICBID_MASTER_QUP_CORE_3,
	ICBID_MASTER_GPDSP_SAIL,
	ICBID_MASTER_COUNT,
	ICBID_MASTER_NONE = ICBID_MASTER_COUNT,
	ICBID_MASTER_SIZE = 0x7FFFFFFF /**< Force to 32 bits */
};

enum icbid_slave {
	ICBID_SLAVE_EBI1 = 0,
	ICBID_SLAVE_MNOC_HF_MEM_NOC,
	ICBID_SLAVE_QUP_2,
	ICBID_SLAVE_QUP_1,
	ICBID_SLAVE_HWKM,
	ICBID_SLAVE_CRYPTO_0_CFG,
	ICBID_SLAVE_SNOC_GEM_NOC_SF,
	ICBID_SLAVE_A1NOC_SNOC,
	ICBID_SLAVE_A2NOC_SNOC,
	ICBID_SLAVE_LLCC,
	ICBID_SLAVE_ANOC_PCIE_GEM_NOC,
	ICBID_SLAVE_CDSP_MEM_NOC,
	ICBID_SLAVE_IPA_CORE,
	ICBID_SLAVE_QUP_0,
	ICBID_SLAVE_QUP_CORE_1,
	ICBID_SLAVE_QUP_CORE_2,
	ICBID_SLAVE_QUP_CORE_0,
	ICBID_SLAVE_GEM_NOC_CNOC,
	ICBID_SLAVE_PKA_WRAPPER_CFG,
	ICBID_SLAVE_PKA_CORE,
	ICBID_SLAVE_HWKM_CORE,
	ICBID_SLAVE_CDSPB_MEM_NOC,
	ICBID_SLAVE_QUP_CORE_3,
	ICBID_SLAVE_QUP_3,
	ICBID_SLAVE_GP_DSP_SAIL_NOC,
	ICBID_SLAVE_COUNT,
	ICBID_SLAVE_NONE = ICBID_SLAVE_COUNT,
	ICBID_SLAVE_SIZE = 0x7FFFFFFF /**< Force to 32 bits */
};

#endif /* QTI_ICBID_H */
