/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef __QFPROM_TARGET_H__
#define __QFPROM_TARGET_H__

#include <platform_config.h>
#include <stddef.h>
#include <stdint.h>
#include <tee_api_types.h>
#include <util.h>

#define QFPROM_RAW_BASE				0x01b40000
#define QFPROM_CORR_BASE			0x01b44000
#define QFPROM_SIZE				0x4000

/* GCC secure-control RCG registers used by the common QFPROM writer. */
#define GCC_SEC_CTRL_CMD_RCGR			0x26030
#define GCC_SEC_CTRL_CFG_RCGR			0x26034

#define QFPROM_BLOW_TIMER_OFFSET		0x203c
#define QFPROM_ACCEL_OFFSET			0x2044
#define QFPROM_BLOW_STATUS_OFFSET		0x2048
#define QFPROM_BLOW_STATUS_RMSK		0x3
#define QFPROM_BLOW_STATUS_BUSY_VAL		0x1
#define QFPROM_BLOW_STATUS_ERROR_VAL		0x2
#define QFPROM_BLOW_STATUS_READY_VAL		0x0
#define QFPROM_FEC_ESR_OFFSET			0x2060
#define QFPROM_FEC_EAR_OFFSET			0x2064
#define QFPROM_FEC_ESR_ERR_SEEN_BMSK		BIT(0)
#define QFPROM_FEC_EAR_ERR_ADDR_BMSK		0xffff

#define QFPROM_BLOW_TIMER_CLK_FREQ_MHZ_X10	48
#define QFPROM_FUSE_BLOW_TIME_IN_US		10
#define QFPROM_GATELAST_VAL			0x1
#define QFPROM_TRIPPT_SEL_VAL			0x4
#define QFPROM_ACCEL_VAL			0x90
#define QFPROM_GATELAST_SHFT			11
#define QFPROM_TRIPPT_SEL_SHFT			8
#define QFPROM_ACCEL_SHFT			0

#define QFPROM_ACCEL_VALUE \
	((QFPROM_GATELAST_VAL << QFPROM_GATELAST_SHFT) | \
	 (QFPROM_TRIPPT_SEL_VAL << QFPROM_TRIPPT_SEL_SHFT) | \
	 (QFPROM_ACCEL_VAL << QFPROM_ACCEL_SHFT))
#define QFPROM_ACCEL_RESET_VALUE \
	(0x1 << QFPROM_GATELAST_SHFT)
#define QFPROM_CLOCK_DIVIDE			0x7

#define QFPROM_RAW_TO_CORR(raw_addr) \
	((raw_addr) + (QFPROM_CORR_BASE - QFPROM_RAW_BASE))

#define LCM_ADDR				0x01b40120
#define PRI_KEY_DERIVATION_KEY_ADDR		0x01b40128
#define MRC_2_0_ADDR				0x01b40170
#define PTE_ADDR				0x01b40180
#define READ_PERMISSION_ADDR			0x01b401a0
#define WRITE_PERMISSION_ADDR			0x01b401a8
#define FEC_ENABLES_ADDR			0x01b401b0
#define OEM_CONFIG_ADDR			0x01b401b8
#define FEATURE_CONFIG_M_ADDR			0x01b401d0
#define ANTI_ROLLBACK_1_ADDR			0x01b40208
#define ANTI_ROLLBACK_2_ADDR			0x01b40210
#define ANTI_ROLLBACK_3_ADDR			0x01b40218
#define ANTI_ROLLBACK_4_ADDR			0x01b40220
#define PK_HASH_0_ADDR				0x01b40228
#define CALIBRATION_ADDR			0x01b40258
#define MEMORY_CONFIGURATION_ADDR		0x01b402e0
#define OEM_IMAGE_ENCRYPTION_KEY_ADDR		0x01b40440
#define OEM_SECURE_BOOT_ADDR			0x01b40458
#define SEC_KEY_DERIVATION_KEY_ADDR		0x01b40468
#define IMAGE_ENCRYPTION_KEY_1_ADDR		0x01b40650
#define USER_KEY_DERIVATION_KEY_ADDR		0x01b40668
#define OEM_SPARE_27_ADDR			0x01b40690
#define OEM_SPARE_28_ADDR			0x01b406a0
#define OEM_SPARE_29_ADDR			0x01b406b0
#define OEM_SPARE_30_ADDR			0x01b406c0
#define OEM_SPARE_31_ADDR			0x01b406d0

#define QFPROM_READ_PERM_LSB_OFFSET \
	(READ_PERMISSION_ADDR - QFPROM_RAW_BASE)
#define QFPROM_READ_PERM_MSB_OFFSET \
	(QFPROM_READ_PERM_LSB_OFFSET + 4)
#define QFPROM_WRITE_PERM_LSB_OFFSET \
	(WRITE_PERMISSION_ADDR - QFPROM_RAW_BASE)
#define QFPROM_WRITE_PERM_MSB_OFFSET \
	(QFPROM_WRITE_PERM_LSB_OFFSET + 4)

#define QFPROM_HW_MUTEX_ID			8
#define QFPROM_HW_MUTEX_PID			1
#define QFPROM_HW_MUTEX_TIMEOUT_US		10000
#define QFPROM_MUTEX_REG_ADDR \
	(TCSR_MUTEX_BASE + (0x1000 * QFPROM_HW_MUTEX_ID))

enum qfprom_region_name {
	QFPROM_CRI_CM_PRIVATE_REGION = 0,
	QFPROM_LCM_REGION = 1,
	QFPROM_PRI_KEY_DERIVATION_KEY_REGION = 2,
	QFPROM_CM_FEATURE_CONFIG_REGION = 3,
	QFPROM_MRC_2_0_REGION = 4,
	QFPROM_PTE_REGION = 5,
	QFPROM_READ_PERMISSION_REGION = 6,
	QFPROM_WRITE_PERMISSION_REGION = 7,
	QFPROM_FEC_ENABLES_REGION = 8,
	QFPROM_OEM_CONFIG_REGION = 9,
	QFPROM_FEATURE_CONFIG_M_REGION = 10,
	QFPROM_ANTI_ROLLBACK_1_REGION = 11,
	QFPROM_ANTI_ROLLBACK_2_REGION = 12,
	QFPROM_ANTI_ROLLBACK_3_REGION = 13,
	QFPROM_ANTI_ROLLBACK_4_REGION = 14,
	QFPROM_PK_HASH_0_REGION = 15,
	QFPROM_CALIBRATION_REGION = 16,
	QFPROM_MEMORY_CONFIGURATION_REGION = 17,
	QFPROM_OEM_IMAGE_ENCRYPTION_KEY_REGION = 21,
	QFPROM_OEM_SECURE_BOOT_REGION = 22,
	QFPROM_SEC_KEY_DERIVATION_KEY_REGION = 23,
	QFPROM_IMAGE_ENCRYPTION_KEY_1_REGION = 25,
	QFPROM_USER_KEY_DERIVATION_KEY_REGION = 26,
	QFPROM_OEM_SPARE_27_REGION = 27,
	QFPROM_OEM_SPARE_28_REGION = 28,
	QFPROM_OEM_SPARE_29_REGION = 29,
	QFPROM_OEM_SPARE_30_REGION = 30,
	QFPROM_OEM_SPARE_31_REGION = 31,
	QFPROM_LAST_REGION_DUMMY,
};

#define LCM_PERM_MASK				BIT(1)
#define PRI_KEY_DERIVATION_KEY_PERM_MASK	BIT(2)
#define MRC_2_0_PERM_MASK			BIT(4)
#define PTE_PERM_MASK				BIT(5)
#define READ_PERMISSION_PERM_MASK		BIT(6)
#define WRITE_PERMISSION_PERM_MASK		BIT(7)
#define FEC_ENABLES_PERM_MASK			BIT(8)
#define OEM_CONFIG_PERM_MASK			BIT(9)
#define FEATURE_CONFIG_M_PERM_MASK		BIT(10)
#define ANTI_ROLLBACK_1_PERM_MASK		BIT(11)
#define ANTI_ROLLBACK_2_PERM_MASK		BIT(12)
#define ANTI_ROLLBACK_3_PERM_MASK		BIT(13)
#define ANTI_ROLLBACK_4_PERM_MASK		BIT(14)
#define PK_HASH_0_PERM_MASK			BIT(15)
#define CALIBRATION_PERM_MASK			BIT(16)
#define MEMORY_CONFIGURATION_PERM_MASK		BIT(17)
#define OEM_IMAGE_ENCRYPTION_KEY_PERM_MASK	BIT(21)
#define OEM_SECURE_BOOT_PERM_MASK		BIT(22)
#define SEC_KEY_DERIVATION_KEY_PERM_MASK	BIT(23)
#define IMAGE_ENCRYPTION_KEY_1_PERM_MASK	BIT(25)
#define USER_KEY_DERIVATION_KEY_PERM_MASK	BIT(26)
#define OEM_SPARE_27_PERM_MASK			BIT(27)
#define OEM_SPARE_28_PERM_MASK			BIT(28)
#define OEM_SPARE_29_PERM_MASK			BIT(29)
#define OEM_SPARE_30_PERM_MASK			BIT(30)
#define OEM_SPARE_31_PERM_MASK			BIT(31)

#define OEM_CONFIG2_OFFSET			0x6048
#define EKU_ENFORCEMENT_EN_SHFT			30
#define SECURE_BOOT_APPS_OFFSET			0x607c
#define SECURE_BOOT_AUTH_EN_BMSK		BIT(5)
#define SECURE_BOOT_USE_SERIAL_NUM_BMSK	BIT(6)
#define JTAG_ID_OFFSET				0x6130
#define JTAG_ID_AUTH_BMSK			GENMASK_32(31, 0)
#define SERIAL_NUM_OFFSET			0x6134
#define OEM_ID_OFFSET				0x6138
#define OEM_ID_BMSK				GENMASK_32(31, 16)
#define OEM_ID_SHFT				16
#define MODEL_ID_BMSK				GENMASK_32(15, 0)
#define MODEL_ID_SHFT				0
#define PK_HASH0_OFFSET				0x6190
#define QFPROM_ROOT_OF_TRUST_BYTE_SIZE		48

#define TCSR_SOC_HW_VERSION_ADDR		0x00348000
#define SOC_HW_VERSION_FAM_DEV_BMSK		0xfff00000
#define SOC_HW_VERSION_FAM_DEV_SHFT		16

#endif /* __QFPROM_TARGET_H__ */
